# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: frost_arm
  joint_model_group_pose: straight
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - left_gripper_joint
    - right_gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
frost_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
frost_hand_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - left_gripper_joint
    - right_gripper_joint
  gains:
    left_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
frost_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint0
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1